### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by arnonuem** [dhamaniasad/crestify#26]
Please update documentation to contain that at least vagrant 1.5.x or higher is needed.

**Comment by dhamaniasad** [comment]
@arnonuem Vagrant 1.5.x came out [three years ago](https://github.com/mitchellh/vagrant/releases/tag/v1.5.1). Do you think we still need to add it in the docs in that case?

**Comment by arnonuem** [comment]
I think its worth adding it since there are old ubuntu machines out there. 
When adding Vagrant via APT the version 1.4.x is installed :/

**Comment by dhamaniasad** [comment]
Closing as Vagrant has been removed.
