### ISSUE TITLE
decouple fabric from vagrant

### ISSUE THREAD

**Issue by satyanash** [dhamaniasad/crestify#32]
Say I decide to self host crestify, I should be able to reuse the existing fab files.
The current fabfile has a direct dependency on vagrant.
We need a way to specify the deployment target dynamically, be it a Vagrant box or a real server.

**Comment by satyanash** [comment]
What is the canonical way to deploy crestify to a remote host right now?

**Comment by dhamaniasad** [comment]
The dependency on Vagrant is not hard. We can rewrite the fabfile to work with other hosts fairly easily, and the same process should work for setting up Crestify on a remote host. I wouldn't want to touch the Postgres part of things when deploying on a remote host though, as there's potential for things going wrong.

**Comment by dfundingsland** [comment]
Rather than Fabric, why not use Ansible instead?

**Comment by dhamaniasad** [comment]
Closing this issue as Vagrant will not be used going forward, and even Fabric might be replaced.
