### ISSUE TITLE
Can't import bookmarks exported from chrome

### ISSUE THREAD

**Issue by yeahsmaggy** [dhamaniasad/crestify#33]
I exported my bookmarks from chrome. They appear to be in the right format. Nothing happens when I try to import. I get redirected to the search screen and nothing happens. No bookmarks imported.

**Comment by dhamaniasad** [comment]
Hey @yeahsmaggy! 

For the imports to work, you need to be running the Celery workers. You'd do that via `honcho start`. Can you try that and let me know if it still doesn't work? 

Apologies for the late response.

**Comment by itsmehemant123** [comment]
Did it work for you @yeahsmaggy ? I'm facing the same issue.

I had to edit all instances of `Tag()` to add userid and text in the constructor (https://github.com/crestify/crestify/blob/master/crestify/services/parsers.py#L84). But then I get another exception - `AttributeError: 'Bookmark' object has no attribute 'tags_relationship'`

**Comment by dhamaniasad** [comment]
Closing in favor of #39
