### ISSUE TITLE
start versioning

### ISSUE THREAD

**Issue by satyanash** [dhamaniasad/crestify#38]
We need to start versioning the app such that people who have it hosted have a better idea of how far behind they are without peering into the source code.

Suggestions:
* Semantic versioning
* use git tags for release versions
* use `bumpversion` to automate the version incrementing
* maintain a `setup.py` that contains the versioning info as well as the packaging details to generate a distributable tarball
* changelogs for every version

**Comment by dhamaniasad** [comment]
- [ ] Semantic versioning
- [ ] use git tags for release versions
- [ ] use `bumpversion` to automate the version incrementing
- [ ] maintain a `setup.py` that contains the versioning info as well as the packaging details to generate a distributable tarball
- [ ] changelogs for every version
